/**
 * Mutation testing gate — 100, the same as the seven backend services, marketplace-common and the two
 * sibling frontends.
 *
 * Coverage proves a line ran. Mutation proves a test would have failed had that line been wrong. The two
 * answers diverge badly: every package on this platform sat at 100% coverage while mutants survived. Do
 * not lower `thresholds.break`, and do not add `ignoreStatic` to silence a survivor — it masks real gaps,
 * and the survivor it appears to fix is usually a load-time mutant that needs a dynamic `await import()`
 * inside `beforeEach` instead.
 *
 * ⚠️ **This repo has no `test/` directory yet**, per the standing "skip all tests" instruction — the same
 * posture as `marketplace-shopowner`. The harness is wired and the threshold is 100; a commit here needs
 * `--no-verify` until the tests exist. That is the intended state and the way out is to write them, never
 * to lower the number or drop the gate.
 *
 * @type {import('@stryker-mutator/api/core').PartialStrykerOptions}
 */
export default {
	testRunner: 'vitest',
	vitest: { configFile: 'vitest.config.ts' },
	coverageAnalysis: 'perTest',
	reporters: ['clear-text', 'progress', 'html'],
	/**
	 * 28 workers on a 32-thread box, matching `marketplace-admin`, where the number was measured rather
	 * than guessed (the `4` it replaced is a copy-paste every backend repo still carries).
	 *
	 * ⚠️ "It still scored 100" is **not** a reason to raise this. A starved worker misses a `waitFor`
	 * deadline, the test fails, and Stryker records the mutant as *killed* — overload inflates the score,
	 * so 100 at any concurrency is consistent with a gate that has quietly stopped checking. Compare the
	 * timeout *set* between two runs instead: same files, same lines, same mutators means the workers were
	 * not starved. And expect swap: jsdom workers cost ~570 MB each.
	 */
	concurrency: 28,
	timeoutMS: 60000,
	thresholds: { high: 100, low: 95, break: 100 },
	// The sandbox is a file-by-file copy of the repo, and `copyFile` refuses a symlink that points at a
	// directory: `.claude/skills/*` are symlinks into `.agents/`, and the first one aborts the whole run
	// with `EISDIR` before a single mutant exists. None of these are inputs to a test anyway.
	//
	// `.qodana` matters beyond its ~23 MB: `disableTypeChecks: true` resolves to a glob matched with
	// `dot: true`, so it descends into dotted directories and every run logged a `ParseError` trying to
	// strip `@ts-` directives out of Qodana's own `thirdPartySoftwareList.html`. Stryker swallows that and
	// carries on, so the gate stayed green while printing a stack trace nobody could act on.
	//
	// `.output` and `.tanstack` are this app's two extras over the SPAs — the Nitro server build and the
	// router plugin's scratch directory, both regenerated and neither an input.
	ignorePatterns: ['.agents', '.claude', '.qodana', '.output', '.tanstack', 'coverage', 'dist'],
	mutate: [
		'src/**/*.{ts,tsx}',
		// graphql-codegen output: `graphql()` document maps and generated types. Mutating a generated file
		// tests the generator, and the mutants are unkillable by design — the document strings are compared
		// by identity, so flipping a character in one produces a document no test can send.
		'!src/gql/**',
		// Generated by the TanStack Router vite plugin from the filenames under `src/routes/`. Same argument
		// as `src/gql/**`, plus it is rewritten on every dev server start.
		'!src/routeTree.gen.ts',
		// The two framework entry points: `hydrateRoot` in the browser and the Nitro request handler on the
		// server. Excluded from coverage for the same reason (see vitest.config.ts) — they run only against a
		// real document or a real socket, and the one thing they could get wrong (mounting or serving the
		// wrong tree) is what every other test already covers.
		'!src/client.tsx',
		'!src/server.ts',
		// A single `Sentry.init` call behind a DSN check. Every mutant of it is either equivalent (the SDK
		// ignores the option) or only observable by asserting the SDK was configured, which asserts that the
		// SDK exists.
		'!src/instrument.ts',
		// One-line re-exports: `createFileRoute('<id>')(<x>RouteOptions)`. The route id is the only mutable
		// token and a wrong one fails to compile against the generated tree, so there is no mutant a test
		// could kill that tsc does not already reject. The behaviour lives in `src/routeOptions/`, which is
		// mutated normally.
		//
		// ⚠️ `.tsx` only, deliberately. The three **`.ts`** files in that directory — `robots[.]txt.ts`,
		// `sitemap[.]xml.ts` and `sitemaps.$kind.$cursor.ts` — are server route handlers with real bodies:
		// cache-control headers, a sitemap shard cursor, an XML document. Excluding the whole directory
		// would take those with it and no gate anywhere else covers them.
		'!src/routes/**/*.tsx',
		// Ambient type declarations. No runtime, nothing to mutate.
		'!src/vite-env.d.ts'
	]
}
