import { fileURLToPath } from 'node:url'

import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

/**
 * One project, jsdom, and deliberately **without** `tanstackStart()` in the plugin list.
 *
 * The framework plugin installs two Vite environments (`client` and `ssr`), a router generator that
 * rewrites `src/routeTree.gen.ts` on start, and a server-function transform. None of that is wanted in
 * a test run: the generator would race the suite for the same file, and the environments turn one
 * vitest project into two builds of everything. What the tests actually exercise is the layer below —
 * the loaders, head builders and search schemas in `src/routeOptions/`, which are plain objects that
 * import nothing from the router. That is exactly why they live there. See README §3.1.
 *
 * Coverage is gated at 100 on all four metrics, the same as every other repo on the platform. The
 * exclusions below are code that is not this app's to test — generated codegen and router output, the
 * two framework entries that only run inside a real server or a real browser, and the Sentry init that
 * is a single side-effecting call.
 */
export default defineConfig({
	plugins: [react()],
	resolve: {
		alias: {
			'@': fileURLToPath(new URL('./src', import.meta.url)),
			'@gql': fileURLToPath(new URL('./src/gql', import.meta.url))
		}
	},
	test: {
		globals: true,
		environment: 'jsdom',
		// Dates on the customer screens are formatted through `Intl`, which reads the ambient zone.
		// Without a fixed one the same assertion passes in Rome and fails in UTC — and the failure is an
		// hour, which reads as a bug in the formatter rather than as a machine difference.
		//
		// The test scripts export `TZ=UTC` as well, and both are needed. This setting reaches the worker
		// through `process.env`, which is enough for vitest's own pool; Stryker's runner uses a pool where
		// assigning `process.env.TZ` does not move ICU's zone.
		env: { TZ: 'UTC' },
		// Order matters: the polyfill has to run before anything imports react-dom, and `vitest.setup.ts`
		// imports it transitively on its second line.
		setupFiles: ['./vitest.polyfill.ts', './vitest.setup.ts'],
		include: ['test/**/*.test.{ts,tsx}'],
		restoreMocks: true,
		// The GraphQL helper replaces `globalThis.fetch`. Without this the replacement outlives the test
		// that installed it, and the next file's first request answers with the previous file's fixture.
		unstubGlobals: true,
		coverage: {
			provider: 'v8',
			reporter: ['text', 'html', 'lcov'],
			include: ['src/**/*.{ts,tsx}'],
			exclude: [
				// Generated by graphql-codegen on every `yarn codegen`. Editing it is pointless and testing
				// it tests the generator.
				'src/gql/**',
				// Written by TanStack Router's generator on every dev-server start and every build. Same
				// argument, and it is not even stable between runs.
				'src/routeTree.gen.ts',
				// The two framework entries. `client.tsx` hydrates a real document and `server.ts` is the
				// request handler the node build wraps — neither has a unit, and the one thing they could
				// get wrong (mounting the wrong router) is what every other test already covers.
				'src/client.tsx',
				'src/server.ts',
				// One-line `createFileRoute(...)(options)` modules. The `options` objects they pass are in
				// src/routeOptions/ and are covered there; what is left in these files is the framework's
				// own registration call, which cannot be exercised without booting the plugin.
				'src/routes/**',
				// A single `Sentry.init` call guarded by a DSN check. Asserting it was called asserts that
				// the SDK exists.
				'src/instrument.ts',
				'src/vite-env.d.ts'
			],
			thresholds: {
				statements: 100,
				branches: 100,
				functions: 100,
				lines: 100
			}
		}
	}
})
