/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountPasswordRouteImport } from './routes/account.password'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password.index'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as ShopsCityRouteImport } from './routes/shops.$city'
import { Route as CategorySlugIndexRouteImport } from './routes/category.$slug.index'
import { Route as CategorySlugChildSlugRouteImport } from './routes/category.$slug.$childSlug'
import { Route as ResetPasswordEmailHashRouteImport } from './routes/reset-password.$email.$hash'
import { Route as ShopSlugIndexRouteImport } from './routes/shop.$slug.index'
import { Route as SitemapsKindCursorRouteImport } from './routes/sitemaps.$kind.$cursor'
import { Route as ShopSlugItemItemSlugRouteImport } from './routes/shop.$slug.item.$itemSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPasswordRoute = AccountPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AccountRoute,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsCityRoute = ShopsCityRouteImport.update({
  id: '/shops/$city',
  path: '/shops/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugIndexRoute = CategorySlugIndexRouteImport.update({
  id: '/category/$slug/',
  path: '/category/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugChildSlugRoute = CategorySlugChildSlugRouteImport.update({
  id: '/category/$slug/$childSlug',
  path: '/category/$slug/$childSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordEmailHashRoute = ResetPasswordEmailHashRouteImport.update({
  id: '/reset-password/$email/$hash',
  path: '/reset-password/$email/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugIndexRoute = ShopSlugIndexRouteImport.update({
  id: '/shop/$slug/',
  path: '/shop/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsKindCursorRoute = SitemapsKindCursorRouteImport.update({
  id: '/sitemaps/$kind/$cursor',
  path: '/sitemaps/$kind/$cursor',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugItemItemSlugRoute = ShopSlugItemItemSlugRouteImport.update({
  id: '/shop/$slug/item/$itemSlug',
  path: '/shop/$slug/item/$itemSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/password': typeof AccountPasswordRoute
  '/shops/$city': typeof ShopsCityRoute
  '/account/': typeof AccountIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/category/$slug/$childSlug': typeof CategorySlugChildSlugRoute
  '/reset-password/$email/$hash': typeof ResetPasswordEmailHashRoute
  '/sitemaps/$kind/$cursor': typeof SitemapsKindCursorRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
  '/shop/$slug/': typeof ShopSlugIndexRoute
  '/shop/$slug/item/$itemSlug': typeof ShopSlugItemItemSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/password': typeof AccountPasswordRoute
  '/shops/$city': typeof ShopsCityRoute
  '/account': typeof AccountIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/shops': typeof ShopsIndexRoute
  '/category/$slug/$childSlug': typeof CategorySlugChildSlugRoute
  '/reset-password/$email/$hash': typeof ResetPasswordEmailHashRoute
  '/sitemaps/$kind/$cursor': typeof SitemapsKindCursorRoute
  '/category/$slug': typeof CategorySlugIndexRoute
  '/shop/$slug': typeof ShopSlugIndexRoute
  '/shop/$slug/item/$itemSlug': typeof ShopSlugItemItemSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/password': typeof AccountPasswordRoute
  '/shops/$city': typeof ShopsCityRoute
  '/account/': typeof AccountIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/category/$slug/$childSlug': typeof CategorySlugChildSlugRoute
  '/reset-password/$email/$hash': typeof ResetPasswordEmailHashRoute
  '/sitemaps/$kind/$cursor': typeof SitemapsKindCursorRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
  '/shop/$slug/': typeof ShopSlugIndexRoute
  '/shop/$slug/item/$itemSlug': typeof ShopSlugItemItemSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/password'
    | '/shops/$city'
    | '/account/'
    | '/reset-password/'
    | '/shops/'
    | '/category/$slug/$childSlug'
    | '/reset-password/$email/$hash'
    | '/sitemaps/$kind/$cursor'
    | '/category/$slug/'
    | '/shop/$slug/'
    | '/shop/$slug/item/$itemSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/password'
    | '/shops/$city'
    | '/account'
    | '/reset-password'
    | '/shops'
    | '/category/$slug/$childSlug'
    | '/reset-password/$email/$hash'
    | '/sitemaps/$kind/$cursor'
    | '/category/$slug'
    | '/shop/$slug'
    | '/shop/$slug/item/$itemSlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/password'
    | '/shops/$city'
    | '/account/'
    | '/reset-password/'
    | '/shops/'
    | '/category/$slug/$childSlug'
    | '/reset-password/$email/$hash'
    | '/sitemaps/$kind/$cursor'
    | '/category/$slug/'
    | '/shop/$slug/'
    | '/shop/$slug/item/$itemSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ShopsCityRoute: typeof ShopsCityRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  CategorySlugChildSlugRoute: typeof CategorySlugChildSlugRoute
  ResetPasswordEmailHashRoute: typeof ResetPasswordEmailHashRoute
  SitemapsKindCursorRoute: typeof SitemapsKindCursorRoute
  CategorySlugIndexRoute: typeof CategorySlugIndexRoute
  ShopSlugIndexRoute: typeof ShopSlugIndexRoute
  ShopSlugItemItemSlugRoute: typeof ShopSlugItemItemSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/password': {
      id: '/account/password'
      path: '/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordRouteImport
      parentRoute: typeof AccountRoute
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$city': {
      id: '/shops/$city'
      path: '/shops/$city'
      fullPath: '/shops/$city'
      preLoaderRoute: typeof ShopsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/': {
      id: '/category/$slug/'
      path: '/category/$slug'
      fullPath: '/category/$slug/'
      preLoaderRoute: typeof CategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/$childSlug': {
      id: '/category/$slug/$childSlug'
      path: '/category/$slug/$childSlug'
      fullPath: '/category/$slug/$childSlug'
      preLoaderRoute: typeof CategorySlugChildSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$email/$hash': {
      id: '/reset-password/$email/$hash'
      path: '/reset-password/$email/$hash'
      fullPath: '/reset-password/$email/$hash'
      preLoaderRoute: typeof ResetPasswordEmailHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug/': {
      id: '/shop/$slug/'
      path: '/shop/$slug'
      fullPath: '/shop/$slug/'
      preLoaderRoute: typeof ShopSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/$kind/$cursor': {
      id: '/sitemaps/$kind/$cursor'
      path: '/sitemaps/$kind/$cursor'
      fullPath: '/sitemaps/$kind/$cursor'
      preLoaderRoute: typeof SitemapsKindCursorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug/item/$itemSlug': {
      id: '/shop/$slug/item/$itemSlug'
      path: '/shop/$slug/item/$itemSlug'
      fullPath: '/shop/$slug/item/$itemSlug'
      preLoaderRoute: typeof ShopSlugItemItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountPasswordRoute: typeof AccountPasswordRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountPasswordRoute: AccountPasswordRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ShopsCityRoute: ShopsCityRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  CategorySlugChildSlugRoute: CategorySlugChildSlugRoute,
  ResetPasswordEmailHashRoute: ResetPasswordEmailHashRoute,
  SitemapsKindCursorRoute: SitemapsKindCursorRoute,
  CategorySlugIndexRoute: CategorySlugIndexRoute,
  ShopSlugIndexRoute: ShopSlugIndexRoute,
  ShopSlugItemItemSlugRoute: ShopSlugItemItemSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
